#-------------------------------------------------------------
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
#-------------------------------------------------------------

# validation:
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate

coverage:
  status:
    patch: no
    project:
      default:
        threshold: 1%
        if_not_found: success
    changes: no
  precision: 2
  range: "50...75"
  ignore:
  - "src/main/java/org/apache/sysds/protobuf"


component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doesn't have a status defined will have a project type one
        target: auto
  individual_components:
    - component_id: module_runtime  # this is an identifier that should not be changed
      name: runtime  # this is a display name, and can be changed freely
      paths:
        - src/main/java/org/apache/sysds/runtime/**
    - component_id: module_matrix # this is an identifier that should not be changed
      name: matrix  # this is a display name, and can be changed freely
      paths:
        - src/main/java/org/apache/sysds/runtime/matrix/**
    - component_id: module_frame # this is an identifier that should not be changed
      name: frame  # this is a display name, and can be changed freely
      paths:
        - src/main/java/org/apache/sysds/runtime/frame/**
    - component_id: module_compress # this is an identifier that should not be changed
      name: compress  # this is a display name, and can be changed freely
      paths:
        - src/main/java/org/apache/sysds/runtime/compress/**
    - component_id: module_compiler  # this is an identifier that should not be changed
      name: compiler  # this is a display name, and can be changed freely
      paths:
        - src/main/java/org/apache/sysds/hops/**
        - src/main/java/org/apache/sysds/lops/**
        - src/main/java/org/apache/sysds/parser/**
    - component_id: module_util  # this is an identifier that should not be changed
      name: util  # this is a display name, and can be changed freely
      paths:
        - src/main/java/org/apache/sysds/api/**
        - src/main/java/org/apache/sysds/common/**
        - src/main/java/org/apache/sysds/conf/**
        - src/main/java/org/apache/sysds/resource/**
        - src/main/java/org/apache/sysds/utils/**