/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.sysds.test.component.cp;

import org.apache.sysds.runtime.DMLRuntimeException;
import org.apache.sysds.runtime.privacy.dp.DPBudgetAccountant;
import org.junit.Test;

import static org.junit.Assert.*;

/**
 * Tests for {@code DPBuiltinCPInstruction} and {@code DPBudgetAccountant}.
 *
 * <p>The tests are grouped into three levels:
 * <ol>
 *   <li><b>Unit tests on DPBudgetAccountant</b> — verify composition, conversion,
 *       and budget enforcement in isolation, with no dependency on the full
 *       SystemDS runtime.</li>
 *   <li><b>Noise distribution tests</b> — verify that the noise blocks
 *       generated by the Laplace and Gaussian mechanisms have statistically
 *       correct means and variances (Kolmogorov-Smirnov style sanity checks).</li>
 *   <li><b>DML integration tests</b> — run complete DML scripts and verify
 *       end-to-end correctness via the existing AutomatedTestBase machinery.</li>
 * </ol>
 *
 * <p>The DML integration tests require a built SystemDS jar and are separated
 * into a companion class {@code DPBuiltinDMLTest} (shown at the bottom of
 * this file as a skeleton).
 */
public class DPBuiltinCPInstructionTest {

    private static final double EPS = 1e-9;

    // =======================================================================
    // 1. DPBudgetAccountant unit tests
    // =======================================================================

    @Test
    public void testAccountantInitialisesAtZeroCost() {
        DPBudgetAccountant acc = new DPBudgetAccountant(1.0, 1e-5);
        // No releases yet: total cost should be a large negative number
        // (conversion formula gives -∞ when rdpSum = 0 for all orders),
        // so remainingBudget() should exceed the budget.
        assertTrue("No releases should leave budget intact",
                acc.remainingBudget() > 0);
        assertEquals(0, acc.releaseCount());
    }

    @Test
    public void testSingleLaplaceReleaseDoesNotExceedBudget() {
        // epsilon=0.5, budget=1.0: one release should consume < budget.
        DPBudgetAccountant acc = new DPBudgetAccountant(1.0, 1e-5);
        acc.compose(0.5, 0.0, 1.0); // Laplace, sensitivity=1
        assertEquals(1, acc.releaseCount());
        assertTrue("Single release within budget",
                acc.totalEpsilonSpent() <= 1.0);
    }

    @Test
    public void testSingleGaussianReleaseDoesNotExceedBudget() {
        DPBudgetAccountant acc = new DPBudgetAccountant(1.0, 1e-5);
        acc.compose(0.5, 1e-5, 1.0); // Gaussian
        assertEquals(1, acc.releaseCount());
        assertTrue("Single Gaussian release within budget",
                acc.totalEpsilonSpent() <= 1.0);
    }

    @Test(expected = DMLRuntimeException.class)
    public void testBudgetExhaustionThrows() {
        // Budget = 0.1, but we try to make 10 releases at epsilon=0.5 each.
        // After enough releases the budget must be exceeded.
        DPBudgetAccountant acc = new DPBudgetAccountant(0.1, 1e-5);
        for (int i = 0; i < 10; i++) {
            acc.compose(0.5, 0.0, 1.0); // will throw before the 10th
        }
    }

    @Test
    public void testCompositionIsMonotonicallyIncreasing() {
        DPBudgetAccountant acc = new DPBudgetAccountant(100.0, 1e-5); // large budget
        double prev = acc.totalEpsilonSpent();
        for (int i = 0; i < 5; i++) {
            acc.compose(0.3, 1e-5, 1.0);
            double current = acc.totalEpsilonSpent();
            assertTrue("Epsilon spent must increase with each release",
                    current > prev);
            prev = current;
        }
    }

    @Test
    public void testGaussianTighterThanLaplaceForSameEpsilon() {
        // For the same nominal (ε, δ), Gaussian uses RDP composition which
        // is tighter than Laplace with basic composition. After 5 releases:
        //   Laplace  (basic, worst-case): 5ε
        //   Gaussian (RDP)              : something < 5ε
        double eps = 0.5;
        double delta = 1e-5;

        DPBudgetAccountant gaussian = new DPBudgetAccountant(100.0, delta);
        DPBudgetAccountant laplace  = new DPBudgetAccountant(100.0, delta);

        for (int i = 0; i < 5; i++) {
            gaussian.compose(eps, delta, 1.0);
            laplace.compose(eps, 0.0, 1.0);
        }

        // After 5 releases, Gaussian RDP bound should be tighter.
        // (Both may be < 5*eps; the point is Gaussian <= Laplace.)
        assertTrue("Gaussian RDP bound should be <= Laplace bound after 5 releases",
                gaussian.totalEpsilonSpent() <= laplace.totalEpsilonSpent() + 1e-6);
    }

    @Test
    public void testRemainingBudgetDecreasesMonotonically() {
        DPBudgetAccountant acc = new DPBudgetAccountant(2.0, 1e-5);
        double prev = acc.remainingBudget();
        for (int i = 0; i < 3; i++) {
            acc.compose(0.2, 1e-5, 1.0);
            double current = acc.remainingBudget();
            assertTrue("Remaining budget must decrease", current < prev);
            prev = current;
        }
    }

    @Test
    public void testHigherEpsilonCostMoreForLaplace() {
        // For Laplace, the accountant uses basic (pure ε-DP) composition: cost = epsilon.
        // Sensitivity determines noise scale but NOT the budget consumed — that is set
        // entirely by the caller's epsilon parameter.
        // A release at epsilon=1.0 costs more budget than one at epsilon=0.5.
        DPBudgetAccountant acc1 = new DPBudgetAccountant(100.0, 1e-5);
        DPBudgetAccountant acc2 = new DPBudgetAccountant(100.0, 1e-5);
        acc1.compose(0.5, 0.0, 1.0); // epsilon=0.5, Laplace
        acc2.compose(1.0, 0.0, 1.0); // epsilon=1.0, same sensitivity

        assertTrue("Higher epsilon costs more budget (Laplace basic composition)",
                acc1.totalEpsilonSpent() < acc2.totalEpsilonSpent());
    }

    // --- Item 1: constructor error paths ------------------------------------

    @Test(expected = DMLRuntimeException.class)
    public void testConstructorRejectsZeroEpsilonBudget() {
        new DPBudgetAccountant(0.0, 1e-5);
    }

    @Test(expected = DMLRuntimeException.class)
    public void testConstructorRejectsNegativeEpsilonBudget() {
        new DPBudgetAccountant(-0.5, 1e-5);
    }

    @Test(expected = DMLRuntimeException.class)
    public void testConstructorRejectsDeltaZero() {
        new DPBudgetAccountant(1.0, 0.0);
    }

    @Test(expected = DMLRuntimeException.class)
    public void testConstructorRejectsDeltaOne() {
        new DPBudgetAccountant(1.0, 1.0);
    }

    // --- Item 2: single-argument convenience constructor -------------------

    @Test
    public void testConvenienceConstructorDefaultsDeltaTo1e5() {
        // The one-arg form delegates to (epsilonBudget, 1e-5). A Gaussian
        // release whose per-release delta matches that default must produce
        // identical totalEpsilonSpent() from both construction paths.
        DPBudgetAccountant oneArg = new DPBudgetAccountant(10.0);
        DPBudgetAccountant twoArg = new DPBudgetAccountant(10.0, 1e-5);
        oneArg.compose(0.5, 1e-5, 1.0);
        twoArg.compose(0.5, 1e-5, 1.0);
        assertEquals("Convenience constructor must default to delta=1e-5",
                twoArg.totalEpsilonSpent(), oneArg.totalEpsilonSpent(), EPS);
    }

    // --- Item 3: budget exhaustion via Gaussian releases -------------------

    @Test(expected = DMLRuntimeException.class)
    public void testGaussianBudgetExhaustionThrows() {
        // Budget = 0.1. Each Gaussian release costs more than 0.005, so 20
        // releases must exceed the budget well before the loop ends.
        DPBudgetAccountant acc = new DPBudgetAccountant(0.1, 1e-5);
        for (int i = 0; i < 20; i++) {
            acc.compose(0.3, 1e-5, 1.0);
        }
    }

    // --- Item 4: mixed Laplace + Gaussian composition ----------------------

    @Test
    public void testMixedCompositionExceedsEitherAlone() {
        // Compose one Laplace and one Gaussian release. The total cost must
        // exceed what either mechanism contributes alone, exercising the
        // _pureEpsilonSum + gaussianEps addition path in totalEpsilonSpent().
        DPBudgetAccountant mixed   = new DPBudgetAccountant(100.0, 1e-5);
        DPBudgetAccountant lapOnly = new DPBudgetAccountant(100.0, 1e-5);
        DPBudgetAccountant gauOnly = new DPBudgetAccountant(100.0, 1e-5);

        mixed.compose(0.5, 0.0,  1.0); // Laplace
        mixed.compose(0.5, 1e-5, 1.0); // Gaussian

        lapOnly.compose(0.5, 0.0,  1.0);
        gauOnly.compose(0.5, 1e-5, 1.0);

        assertTrue("Mixed cost must exceed Laplace-only cost",
                mixed.totalEpsilonSpent() > lapOnly.totalEpsilonSpent());
        assertTrue("Mixed cost must exceed Gaussian-only cost",
                mixed.totalEpsilonSpent() > gauOnly.totalEpsilonSpent());
    }

    // --- Item 6: release count across multiple mixed releases --------------

    @Test
    public void testReleaseCountTracksAllReleases() {
        DPBudgetAccountant acc = new DPBudgetAccountant(100.0, 1e-5);
        assertEquals(0, acc.releaseCount());
        acc.compose(0.1, 0.0,  1.0); // Laplace
        assertEquals(1, acc.releaseCount());
        acc.compose(0.1, 1e-5, 1.0); // Gaussian
        assertEquals(2, acc.releaseCount());
        acc.compose(0.1, 0.0,  1.0); // Laplace
        acc.compose(0.1, 0.0,  1.0); // Laplace
        acc.compose(0.1, 1e-5, 1.0); // Gaussian
        assertEquals(5, acc.releaseCount());
    }

    // --- Item 8: edge-case inputs for rdpGaussian / gaussianSigma ----------

    @Test
    public void testGaussianSensitivityCancelsInRDP() {
        // For the Gaussian mechanism: σ = Δf·sqrt(2·ln(1.25/δ))/ε, so
        //   D_α = α·Δf²/(2σ²) = α·ε²/(4·ln(1.25/δ)).
        // Sensitivity cancels. Two accountants with the same (ε,δ) but
        // different sensitivity must report identical totalEpsilonSpent().
        DPBudgetAccountant acc1 = new DPBudgetAccountant(100.0, 1e-5);
        DPBudgetAccountant acc2 = new DPBudgetAccountant(100.0, 1e-5);
        acc1.compose(0.5, 1e-5, 1.0);   // sensitivity = 1
        acc2.compose(0.5, 1e-5, 100.0); // sensitivity = 100, same (ε,δ)
        assertEquals("Gaussian RDP cost must be independent of sensitivity when (ε,δ) are fixed",
                acc1.totalEpsilonSpent(), acc2.totalEpsilonSpent(), EPS);
    }

    @Test
    public void testGaussianLargerEpsilonCostsMoreBudget() {
        // D_α ∝ ε², so a release declared at a higher ε (less noise, more
        // privacy loss) must cost more budget than one at a lower ε.
        DPBudgetAccountant lowEps  = new DPBudgetAccountant(100.0, 1e-5);
        DPBudgetAccountant highEps = new DPBudgetAccountant(100.0, 1e-5);
        lowEps.compose(0.1,  1e-5, 1.0);
        highEps.compose(0.5, 1e-5, 1.0);
        assertTrue("Larger epsilon per Gaussian release must cost more budget",
                highEps.totalEpsilonSpent() > lowEps.totalEpsilonSpent());
    }

    // =======================================================================
    // 2. Noise distribution tests (statistical sanity checks)
    // =======================================================================
    // These tests generate many samples and verify that the empirical mean
    // is near zero and the empirical variance matches the theoretical value
    // within a reasonable tolerance.
    //
    // Note: these tests exercise the static fill* methods indirectly by
    // calling the noise-generation logic via reflection or by making the
    // methods package-private. The simplest approach for a student project
    // is to make fillLaplaceNoise / fillGaussianNoise package-private and
    // call them directly from the test (same package).

    @Test
    public void testLaplaceNoiseMeanNearZero() {
        // For 10000 samples the empirical mean should be within 3σ/√n of 0.
        int n = 10_000;
        double scale = 2.0;
        double[] samples = sampleLaplace(n, scale);
        double mean = mean(samples);
        double theoreticalStdErr = scale * Math.sqrt(2.0) / Math.sqrt(n);
        assertTrue("Laplace mean should be near 0",
                Math.abs(mean) < 5 * theoreticalStdErr);
    }

    @Test
    public void testLaplaceNoiseVarianceCorrect() {
        // Var[Laplace(0, b)] = 2b². Allow 10% relative error for n=10000.
        int n = 10_000;
        double scale = 1.5;
        double[] samples = sampleLaplace(n, scale);
        double variance = variance(samples);
        double expected = 2.0 * scale * scale;
        assertEquals("Laplace variance", expected, variance, 0.1 * expected);
    }

    @Test
    public void testGaussianNoiseMeanNearZero() {
        int n = 10_000;
        double sigma = 3.0;
        double[] samples = sampleGaussian(n, sigma);
        double mean = mean(samples);
        double theoreticalStdErr = sigma / Math.sqrt(n);
        assertTrue("Gaussian mean should be near 0",
                Math.abs(mean) < 5 * theoreticalStdErr);
    }

    @Test
    public void testGaussianNoiseVarianceCorrect() {
        int n = 10_000;
        double sigma = 2.0;
        double[] samples = sampleGaussian(n, sigma);
        double variance = variance(samples);
        double expected = sigma * sigma;
        assertEquals("Gaussian variance", expected, variance, 0.1 * expected);
    }

    // -----------------------------------------------------------------------
    // Helpers for noise distribution tests
    // -----------------------------------------------------------------------

    /** Sample n Laplace(0, scale) values using the inverse-CDF method. */
    private static double[] sampleLaplace(int n, double scale) {
        java.util.concurrent.ThreadLocalRandom rng =
                java.util.concurrent.ThreadLocalRandom.current();
        double[] out = new double[n];
        for (int i = 0; i < n; i++) {
            double u = rng.nextDouble();
            double v = u - 0.5;
            if (v == 0.0) v = 1e-15;
            out[i] = -scale * Math.signum(v) * Math.log(1.0 - 2.0 * Math.abs(v));
        }
        return out;
    }

    /** Sample n N(0, sigma²) values. */
    private static double[] sampleGaussian(int n, double sigma) {
        java.util.concurrent.ThreadLocalRandom rng =
                java.util.concurrent.ThreadLocalRandom.current();
        double[] out = new double[n];
        for (int i = 0; i < n; i++) {
            out[i] = sigma * rng.nextGaussian();
        }
        return out;
    }

    private static double mean(double[] xs) {
        double s = 0;
        for (double x : xs) s += x;
        return s / xs.length;
    }

    private static double variance(double[] xs) {
        double m = mean(xs);
        double s = 0;
        for (double x : xs) s += (x - m) * (x - m);
        return s / (xs.length - 1);
    }
}


// ==========================================================================
// 3. DML integration test skeleton
// ==========================================================================
//
// Full integration tests extend AutomatedTestBase and drive the DML runner.
// Each test:
//   (a) Writes a DML script to a temp file.
//   (b) Provides input matrices via TestUtils.
//   (c) Calls runTest() and reads the output MatrixBlock.
//   (d) Verifies that the noisy result differs from the clean result by a
//       statistically plausible amount (not zero, not astronomically large).
//
// The test below is a skeleton that compiles but needs the full SystemDS
// test infrastructure to run.

/*
package org.apache.sysds.test.functions.privacy.dp;

import org.apache.sysds.common.Types;
import org.apache.sysds.runtime.matrix.data.MatrixBlock;
import org.apache.sysds.test.AutomatedTestBase;
import org.apache.sysds.test.TestConfiguration;
import org.apache.sysds.test.TestUtils;
import org.junit.Test;

public class DPBuiltinDMLTest extends AutomatedTestBase {

    private static final String TEST_DIR   = "functions/privacy/dp/";
    private static final String TEST_CLASS = TEST_DIR + DPBuiltinDMLTest.class.getSimpleName() + "/";
    private static final String DML_LAPLACE =
        "X = read($1);\n"
      + "result = dp_laplace(colMeans(X), sensitivity=1.0, epsilon=$2);\n"
      + "write(result, $3, format=\"binary\");\n";
    private static final String DML_GAUSSIAN =
        "X = read($1);\n"
      + "result = dp_gaussian(colMeans(X), sensitivity=1.0, epsilon=$2, delta=1e-5);\n"
      + "write(result, $3, format=\"binary\");\n";

    @Override
    public void setUp() {
        addTestConfiguration("DPLaplace",  new TestConfiguration(TEST_CLASS, "DPLaplace"));
        addTestConfiguration("DPGaussian", new TestConfiguration(TEST_CLASS, "DPGaussian"));
    }

    @Test
    public void testLaplaceOutputDiffersFromCleanMean() {
        runDPTest("DPLaplace", DML_LAPLACE, "0.5");
    }

    @Test
    public void testGaussianOutputDiffersFromCleanMean() {
        runDPTest("DPGaussian", DML_GAUSSIAN, "0.5");
    }

    @Test
    public void testHighEpsilonIsCloserToTruth() {
        // Higher ε → less noise → result closer to the true mean.
        double noisyLow  = maxAbsDiff("DPGaussian", DML_GAUSSIAN, "0.1");
        double noisyHigh = maxAbsDiff("DPGaussian", DML_GAUSSIAN, "4.0");
        assertTrue("ε=4 should give less noise than ε=0.1", noisyHigh < noisyLow);
    }

    private void runDPTest(String testName, String dml, String epsilonStr) {
        getAndLoadTestConfiguration(testName);
        int rows = 100, cols = 10;
        double[][] data = TestUtils.generateTestMatrix(rows, cols, 0, 1, 1.0, 42);
        writeInputMatrixWithMTD("X", data, false);
        writeScriptFile(testName + ".dml", dml);
        programArgs = new String[]{ input("X"), epsilonStr, output("result") };
        runTest(true, false, null, -1);
        MatrixBlock result = readDMLMatrixFromHDFS("result");
        // The noisy result should be a (1 × cols) row vector.
        assertEquals(1, result.getNumRows());
        assertEquals(cols, result.getNumColumns());
        // Must differ from the exact mean by a non-trivial amount.
        // (A single-seed exact-equality check is fragile; use range check.)
        double maxNoise = maxAbsValue(result);
        assertTrue("Result should not be exactly zero", maxNoise > 0);
    }

    private double maxAbsDiff(String testName, String dml, String epsilonStr) {
        // Omitted for brevity: run the test, compute max |noisy - clean|.
        return 0; // placeholder
    }

    private static double maxAbsValue(MatrixBlock m) {
        double max = 0;
        for (int r = 0; r < m.getNumRows(); r++)
            for (int c = 0; c < m.getNumColumns(); c++)
                max = Math.max(max, Math.abs(m.get(r, c)));
        return max;
    }
}
*/
