# -------------------------------------------------------------
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# -------------------------------------------------------------

# Autogenerated By   : src/main/python/generator/generator.py
# Autogenerated From : scripts/builtin/cooccurrenceMatrix.dml

from typing import Dict, Iterable

from systemds.operator import OperationNode, Matrix, Frame, List, MultiReturn, Scalar
from systemds.utils.consts import VALID_INPUT_TYPES


def cooccurrenceMatrix(input: Frame,
                       maxTokens: int,
                       windowSize: int,
                       distanceWeighting: bool,
                       symmetric: bool):
    """
     Cleans and processes text data by removing punctuation, converting it to lowercase, and reformatting.
     Adds an index column to the result. The implementation is based on
     https://github.com/stanfordnlp/GloVe/blob/master/src/cooccur.c
    
    
    
    :param S: (Frame[Unknown]): 1D input data frame containing text data.
    :return: (Frame[Unknown]): Processed text data with an index column.
    """

    params_dict = {'input': input, 'maxTokens': maxTokens, 'windowSize': windowSize, 'distanceWeighting': distanceWeighting, 'symmetric': symmetric}
    
    vX_0 = Matrix(input.sds_context, '')
    vX_1 = Frame(input.sds_context, '')
    output_nodes = [vX_0, vX_1, ]

    op = MultiReturn(input.sds_context, 'cooccurrenceMatrix', output_nodes, named_input_nodes=params_dict)

    vX_0._unnamed_input_nodes = [op]
    vX_1._unnamed_input_nodes = [op]

    return op
