# -------------------------------------------------------------
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# -------------------------------------------------------------

# Autogenerated By   : src/main/python/generator/generator.py
# Autogenerated From : scripts/builtin/deepWalk.dml

from typing import Dict, Iterable

from systemds.operator import OperationNode, Matrix, Frame, List, MultiReturn, Scalar
from systemds.utils.consts import VALID_INPUT_TYPES


def deepWalk(Graph: Matrix,
             w: int,
             d: int,
             gamma: int,
             t: int,
             **kwargs: Dict[str, VALID_INPUT_TYPES]):
    """
     This script performs DeepWalk on a given graph (https://arxiv.org/pdf/1403.6652.pdf)
    
    
    
    :param Graph: adjacency matrix of a graph (n x n)
    :param w: window size
    :param d: embedding size
    :param gamma: walks per vertex
    :param t: walk length
    :param lr: learning rate
    :param beta: factor for decreasing learning rate
    :return: matrix of vertex/word representation (n x d)
    """

    params_dict = {'Graph': Graph, 'w': w, 'd': d, 'gamma': gamma, 't': t}
    params_dict.update(kwargs)
    return Matrix(Graph.sds_context,
        'deepWalk',
        named_input_nodes=params_dict)
