# -------------------------------------------------------------
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# -------------------------------------------------------------

# Autogenerated By   : src/main/python/generator/generator.py
# Autogenerated From : scripts/builtin/glmPredict.dml

from typing import Dict, Iterable

from systemds.operator import OperationNode, Matrix, Frame, List, MultiReturn, Scalar
from systemds.script_building.dag import OutputType
from systemds.utils.consts import VALID_INPUT_TYPES


def glmPredict(X: Matrix,
               B: Matrix,
               **kwargs: Dict[str, VALID_INPUT_TYPES]):
    """
    :param dfam: GLM distribution family: 1 = Power, 2 = Binomial, 3 = Multinomial Logit
    :param vpow: Power for Variance defined as (mean)^power (ignored if dfam != 1):
    :param link: Link function code: 0 = canonical (depends on distribution), 1 = Power,
    :param lpow: Power for Link function defined as (mean)^power (ignored if link != 1):
    :param disp: Dispersion value, when available
    :param verbose: Print statistics to stdout
    :return: 'OperationNode' containing printed one per each line, in the following  & string identifier for the statistic, see the table below. & optional integer value that specifies the y-column for per-column statistics; & binomial/multinomial one-column y input is converted into multi-column. & optional boolean value (true or false) that tells us whether or not the input & value of the statistic. & meaning 
    """
    params_dict = {'X': X, 'B': B}
    params_dict.update(kwargs)
    return Matrix(X.sds_context,
        'glmPredict',
        named_input_nodes=params_dict)
