# -------------------------------------------------------------
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# -------------------------------------------------------------

# Autogenerated By   : src/main/python/generator/generator.py
# Autogenerated From : scripts/builtin/smote.dml

from typing import Dict, Iterable

from systemds.operator import OperationNode, Matrix, Frame, List, MultiReturn, Scalar
from systemds.script_building.dag import OutputType
from systemds.utils.consts import VALID_INPUT_TYPES


def smote(X: Matrix,
          mask: Matrix,
          **kwargs: Dict[str, VALID_INPUT_TYPES]):
    """
     Builtin function for handing class imbalance using Synthetic Minority Over-sampling Technique (SMOTE)
     by Nitesh V. Chawla et. al. In Journal of Artificial Intelligence Research 16 (2002). 321–357
    
    
    
    :param X: Matrix of minority class samples
    :param mask: 0/1 mask vector where 0 represent numeric value and 1 represent categorical value
    :param s: Amount of SMOTE (percentage of oversampling), integral multiple of 100
    :param k: Number of nearest neighbor
    :param verbose: if the algorithm should be verbose
    :return: Matrix of (N/100)-1 * nrow(X) synthetic minority class samples
    """

    params_dict = {'X': X, 'mask': mask}
    params_dict.update(kwargs)
    return Matrix(X.sds_context,
        'smote',
        named_input_nodes=params_dict)
