name: Docker pub

on:
  push: 
    branches: main
  workflow_dispatch:
  # Run tests for any PRs.
  pull_request:
    branches: main

env:
  # Image name used while building docker image
  IMAGE_NAME: sysds

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test-job:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: ./docker/build.sh


    
